build:
  image: ubuntu:latest
  stage: build
  variables:
    QT_NAME: qt6
    QT_VERSION: 6.2.0
    QT_PLATFORM: gcc_64
    DEBIAN_FRONTEND: noninteractive # Stop tzdata asking for user input

  before_script:
    - apt update
    - apt install -y libgl1-mesa-dev libasio-dev libxkbcommon-x11-0 cmake build-essential libglib2.0-0 libfontconfig1 libdbus-1-3
    - cmake -P .gitlab/qt_downloader.txt
    - export CMAKE_PREFIX_PATH="${CI_PROJECT_DIR}/${QT_NAME}/${QT_VERSION}/${QT_PLATFORM}/lib/cmake"
    
  script:
    - mkdir build && cd build
    - cmake configure ../ -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --target Fortress Server -j `nproc`