# Based on https://gist.github.com/cristianadam/49dfee3ce6fd359cda5f3b44e0d93536 
# and https://www.qt.io/blog/building-qt-creator-plugins-with-github-actions

name: Qt Cmake Build

on:
  workflow_dispatch:
  push:
    pull_request:
    tags:
      - v*
env:
  QT_NAME: qt6
  QT_VERSION: 6.2.2
  CMAKE_VERSION: 3.21.1
  NINJA_VERSION: 1.10.2
  BUILD_TYPE: Release

  DESKTOP_APP_TARGET: Fortress
  SERVER_APP_TARGET: Server
  DESKTOP_APP_BUILD_FILE: app/Fortress
  SERVER_APP_BUILD_FILE: server/Server

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - name: "Linux Latest x64"
            artifact: "Linux-x64.tar.gz"
            bundle_name: "Linux-x64"
            os: ubuntu-latest,
            cc: "gcc"
            cxx: "g++"
          
          - name: "macOS Latest x64"
            artifact: "macOS-x64.zip"
            bundle_name: "macOS-x64"
            os: macos-latest,
            cc: "clang"
            cxx: "clang++"
          
          - name: "Windows Latest x64"
            artifact: "win-x64.zip"
            bundle_name: "win-x64"
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
            os: windows-latest,
            cc: "cl"
            cxx: "cl"
    steps:
      - uses: actions/checkout@v2

      - name: Installing Dependency
        shell: bash
        run: |
          if [ "$RUNNER_OS" == Linux ]; then
            sudo apt update
            sudo apt install -y libgl1-mesa-dev libxkbcommon-x11-0
            wget https://github.com/QuasarApp/CQtDeployer/releases/download/1.5.1/CQtDeployer_1.5.1_Linux64.zip 
            unzip CQtDeployer*.zip -d cqtdeployer
            chmod +x cqtdeployer/cqtdeployer.sh cqtdeployer/bin/*
          fi
      - name: Download Ninja and CMake
        shell: cmake -P {0}
        run: |
          set(cmake_version $ENV{CMAKE_VERSION})
          set(ninja_version $ENV{NINJA_VERSION})
          message(STATUS "Using host CMake version: ${CMAKE_VERSION}")
          if ("${{ runner.os }}" STREQUAL "Windows")
            set(ninja_suffix "win.zip")
            set(cmake_suffix "windows-x86_64.zip")
            set(cmake_dir "cmake-${cmake_version}-windows-x86_64/bin")
          elseif ("${{ runner.os }}" STREQUAL "Linux")
            set(ninja_suffix "linux.zip")
            set(cmake_suffix "linux-x86_64.tar.gz")
            set(cmake_dir "cmake-${cmake_version}-linux-x86_64/bin")
          elseif ("${{ runner.os }}" STREQUAL "macOS")
            set(ninja_suffix "mac.zip")
            set(cmake_suffix "macos-universal.tar.gz")
            set(cmake_dir "cmake-${cmake_version}-macos-universal/CMake.app/Contents/bin")
          endif()
          set(ninja_url "https://github.com/ninja-build/ninja/releases/download/v${ninja_version}/ninja-${ninja_suffix}")
          file(DOWNLOAD "${ninja_url}" ./ninja.zip SHOW_PROGRESS)
          execute_process(COMMAND ${CMAKE_COMMAND} -E tar xvf ./ninja.zip)
          set(cmake_url "https://github.com/Kitware/CMake/releases/download/v${cmake_version}/cmake-${cmake_version}-${cmake_suffix}")
          file(DOWNLOAD "${cmake_url}" ./cmake.zip SHOW_PROGRESS)
          execute_process(COMMAND ${CMAKE_COMMAND} -E tar xvf ./cmake.zip)
          # Add to PATH environment variable
          file(TO_CMAKE_PATH "$ENV{GITHUB_WORKSPACE}/${cmake_dir}" cmake_dir)
          set(path_separator ":")
          if ("${{ runner.os }}" STREQUAL "Windows")
            set(path_separator ";")
          endif()
          file(APPEND "$ENV{GITHUB_PATH}" "$ENV{GITHUB_WORKSPACE}${path_separator}${cmake_dir}")
          if (NOT "${{ runner.os }}" STREQUAL "Windows")
            execute_process(
              COMMAND chmod +x ninja
              COMMAND chmod +x ${cmake_dir}/cmake
            )
          endif()

      - name: Download Qt
        id: qt
        shell: cmake -P {0}
        run: | # Cmake script:
          set(qt_version $ENV{QT_VERSION})
          set(qt_name $ENV{QT_NAME})
          string(REPLACE "." "" qt_version_dotless "${qt_version}")

          if ("${{ runner.os }}" STREQUAL "Linux")
           set(url_os "linux_x64")
           set(qt_package_name "qt.${qt_name}.${qt_version_dotless}.gcc_64")
           set(qt_dir_prefix "${qt_version}/gcc_64")
           set(compiler "gcc_64")
          elseif ("${{ runner.os }}" STREQUAL "macOS")
           set(url_os "mac_x64")
           set(qt_package_name "qt.${qt_name}.${qt_version_dotless}.clang_64")
           set(qt_dir_prefix "${qt_version}/macos")
           set(compiler "clang_64")
          elseif ("${{ runner.os }}" STREQUAL "Windows")
           set(url_os "windows_x86")
           set(qt_package_name "qt.${qt_name}.${qt_version_dotless}.win64_msvc2019_64")
           set(qt_dir_prefix "${qt_version}/msvc2019_64")
           set(compiler "msvc2019_64")
          endif()
          
          set(qt_base_url "https://download.qt.io/online/qtsdkrepository/${url_os}/desktop/${qt_name}_${qt_version_dotless}")
          set(qt_addon_prefix "qt.${qt_name}.${qt_version_dotless}.addons")

          # Download the manifest file to read which packages are available to download
          file(DOWNLOAD "${qt_base_url}/Updates.xml" ./Updates.xml SHOW_PROGRESS)
          file(READ ./Updates.xml updates_xml)
          
          string(REGEX MATCH "<Name>${qt_package_name}.*<Version>([0-9+-.]+)</Version>.*<DownloadableArchives>qtbase([a-zA-Z0-9_-]+).7z"
            update_xml_output "${updates_xml}")

          set(package_version ${CMAKE_MATCH_1})
          set(package_suffix ${CMAKE_MATCH_2})
          
          message("Package: ${package_version} ${package_suffix}")
          
          string(REPLACE "-debug-symbols" "" package_suffix "${package_suffix}")

          # Workaround for CMake's greedy regex (WinOnly)
          if ("${{ runner.os }}" STREQUAL "Windows")
            string(REPLACE "ARM64" "X86_64" package_suffix "${package_suffix}")
          endif()
          file(MAKE_DIRECTORY ${qt_name})

          # Save the path for other steps
          file(TO_CMAKE_PATH "$ENV{GITHUB_WORKSPACE}/${qt_name}/${qt_dir_prefix}" qt_dir)
          message("::set-output name=qt_dir::${qt_dir}")

          execute_process(COMMAND sh -c "echo 'QT_DIR=${qt_dir}' >> $GITHUB_ENV")

          # Download packages
          message("Downloading packages...")
          foreach(package qtbase qtdeclarative qttools qtquickcontrols2)
            set(addon_url "${qt_base_url}/${qt_package_name}/${package_version}${package}${package_suffix}.7z")
            file (DOWNLOAD "${addon_url}" "./${package}.7z" SHOW_PROGRESS)
            execute_process(COMMAND ${CMAKE_COMMAND} -E tar xvf ../${package}.7z WORKING_DIRECTORY "${qt_name}")
          endforeach()
          
          # Download QtCharts
          message("Donwloading QtCharts")
          foreach (addon qtcharts)
            if ("${{ runner.os }}" STREQUAL "Windows")
              set(addon_url ${qt_base_url}/${qt_addon_prefix}.${addon}.win64_${compiler}/${package_version}${addon}${package_suffix}.7z)
            else() 
              set(addon_url ${qt_base_url}/${qt_addon_prefix}.${addon}.${compiler}/${package_version}${addon}${package_suffix}.7z)
            endif()
          
            message("${addon_url}")
            file (DOWNLOAD "${addon_url}" "./${addon}.7z" SHOW_PROGRESS)
            execute_process(COMMAND ${CMAKE_COMMAND} -E tar xvf ../${addon}.7z WORKING_DIRECTORY "${qt_name}")
          endforeach()

          # uic depends on libicu56.so
          if ("${{ runner.os }}" STREQUAL "Linux")
            file(DOWNLOAD 
              "${qt_base_url}/${qt_package_name}/${package_version}icu-linux-Rhel7.2-x64.7z" 
              "./icu.7z" SHOW_PROGRESS)
              execute_process(COMMAND ${CMAKE_COMMAND} -E tar xvf ../icu.7z WORKING_DIRECTORY "${qt_name}")
          endif()
          
          # Not working anymore with Qt 6.2.2
          # file(READ "${qt_name}/${qt_dir_prefix}/mkspecs/qconfig.pri" qtconfig)
          # string(REPLACE "Enterprise" "OpenSource" qtconfig "${qtconfig}")
          # string(REPLACE "licheck.exe" "" qtconfig "${qtconfig}")
          # string(REPLACE "licheck64" "" qtconfig "${qtconfg}")
          # string(REPLACE "licheck_mac" "" qtconfig "${qtconfig}")
          # file(WRITE "${qt_name}/${qt_dir_prefix}/mkspecs/qconfig.pri" "${qtconfig}")

      - name: Configure
        shell: cmake -P {0}
        run: |
          if ("${{ runner.os }}" STREQUAL "Windows" AND NOT "x${{ matrix.config.environment_script }}" STREQUAL "x")
            execute_process(
              COMMAND "${{ matrix.config.environment_script }}" && set
              OUTPUT_FILE environment_script_output.txt
            )
            file(STRINGS environment_script_output.txt output_lines)

            foreach(line IN LISTS output_lines)
              if (line MATCHES "^([a-zA-Z0-9_-]+)=(.*)$")
                set(ENV{${CMAKE_MATCH_1}} "${CMAKE_MATCH_2}")
              endif()
            endforeach()
          endif()

          set(path_separator ":")
          if ("${{ runner.os }}" STREQUAL "Windows")
            set(path_separator ";")
          endif()
          set(ENV{PATH} "$ENV{GITHUB_WORKSPACE}${path_separator}$ENV{PATH}")

          set(cmake_prefix_path $ENV{QT_DIR}/lib/cmake)

          execute_process(
             COMMAND cmake
              -S .
              -B build
              -D CMAKE_BUILD_TYPE=$ENV{BUILD_TYPE}
              -D CMAKE_PREFIX_PATH=${cmake_prefix_path}
            RESULT_VARIABLE result
          )
          if (NOT result EQUAL 0)
            message(FATAL_ERROR "Bad exit status")
          endif()
          
      - name: Build
        shell: cmake -P {0}
        run: |
          set(ENV{CC} ${{ matrix.config.cc }})
          set(ENV{CXX} ${{ matrix.config.cxx }})
          
          include(ProcessorCount)
          ProcessorCount(N) 
          
          set(make_cmd make $ENV{DESKTOP_APP_TARGET} $ENV{SERVER_APP_TARGET} -j ${N})
          execute_process(COMMAND ${make_cmd} WORKING_DIRECTORY build RESULT_VARIABLE result)
          
          if (NOT result EQUAL 0)
            message(FATAL_ERROR "Bad exit status")
          endif()

      - name: Bundle
        run: |
          bundle_dir=${{ matrix.config.bundle_name }}
          mkdir ${bundle_dir}

          if [ $RUNNER_OS == "Linux" ]; then
            mkdir ${bundle_dir}/Fortress
            ./cqtdeployer/cqtdeployer.sh -bin ./build/${DESKTOP_APP_BUILD_FILE} -qmlDir ./qml -targetDir ${bundle_dir}/Fortress
            mv ./build/${SERVER_APP_BUILD_FILE} ./${bundle_dir}
            tar -cvf ${{ matrix.config.artifact }} ./${bundle_dir}

          elif [ "$RUNNER_OS" == macOS ]; then
            # Fix macdeployqt not copying this framework
            mkdir ./build/app/Fortress.app/Contents/Frameworks/
            cp -r ${{ steps.qt.outputs.qt_dir }}/lib/QtQuickControls2Impl.framework ./build/app/Fortress.app/Contents/Frameworks/
            ${{ steps.qt.outputs.qt_dir }}/bin/macdeployqt ./build/${DESKTOP_APP_BUILD_FILE}.app -qmldir=./qml -dmg
            mv ./build/${DESKTOP_APP_BUILD_FILE}.dmg ${bundle_dir}
            mv ./build/${SERVER_APP_BUILD_FILE} ${bundle_dir}
            zip -r ${{ matrix.config.artifact }} ./${bundle_dir} 
          fi

      - uses: actions/upload-artifact@v2
        id: upload_artifact
        with:
          path: ./${{ matrix.config.artifact}}
          name: ${{ matrix.config.artifact }}

  release:
    name: Release
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

      - name: Store Release URL
        run: |
          echo "${{ steps.create_release.outputs.upload_url }}" > ./upload_url

      - uses: actions/upload-artifact@v1
        with:
          path: ./upload_url
          name: upload_url

  publish:
    if: contains(github.ref, 'tags/v')

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - name: "Linux Latest x64"
            artifact: Linux-x64.tar.gz
            os: ubuntu-latest
          - name: "macOS Latest x64"
            artifact: "macOS-x64.zip"
            os: ubuntu-latest
    needs: release

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: ${{ matrix.config.artifact }}
          path: ./

      - name: Download URL
        uses: actions/download-artifact@v1
        with:
          name: upload_url
          path: ./

      - id: set_upload_url
        run: |
          upload_url=`cat ./upload_url`
          echo ::set-output name=upload_url::$upload_url

      - name: Upload to Release
        id: upload_to_release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.set_upload_url.outputs.upload_url }}
          asset_path: ./${{ matrix.config.artifact }}
          asset_name: ${{ matrix.config.artifact }}
          asset_content_type: application/zip
    
